
# Filter Words Exercise
# =====================
# 
# This builds on the "filter words" exercise from the "Looping Patterns" lecture. You should considering doing that exercise first if you haven't done so already.
# 
# In this exercise, we want to print out the words from the following string that start with "o", ignoring case.


lyrics = '''My Bonnie lies over the ocean.
            My Bonnie lies over the sea.
            My Bonnie lies over the ocean.
            Oh bring back my Bonnie to me.
            '''

# Let's normalize case and remove punctuation
lyrics = lyrics.lower()
lyrics = lyrics.replace('.',"")
lyrics = lyrics.replace(',',"")


# Question 1
# ----------
# 
# This can be done with a `for` loop as follows:
# 
#     words = lyrics.split()
#     o_words = []
#     for word in words:
#         if word[0] == "o":
#             o_words.append(word)
# 
# Re-write this to use a list comprehension instead.


o_words = [word for word in lyrics.split() if word[0] == "o"]



print "words that start with 'o':"
print o_words


# Question 2
# ----------
# 
# Several words are repeated in the result generated by the list comprehension. Cast your list to another Python standard datastructure that will enforce uniqueness.


# your code goes here
print list(set(o_words))

# Question 3
# ----------
# 
# If we are always going to collect all the words and then remove duplicates, we could build a set directly rather than going through a list. Use a set comprehension (or a generator expression if you are using an older version of Python) to produce the set of words that start with "o".


# your code goes here

unique_o_words = { word for word in lyrics.split() if word[0] == "o"}


print "unique words that start with 'o':"
print unique_o_words


# Question 4
# ----------
# 
# Use a dictionary comprehension (or generator expression) to produce a dictionary whose keys are the words that start with "o" and whose values are the number of times the word is repeated.


# your code goes here

o_word_frequencies = {word: lyrics.split().count(word) for word in set(lyrics.split()) if word[0] == "o" }

print "unique words that start with 'o':"
print o_word_frequencies

